version: '3.3'
services:
  icinga-nms:
    hostname: icinga-nms
    restart: always
    image: neszt/icinga-nms-docker:$VERSION
    ports:
      - "$NMS_PORT:8080"
    environment:
      - ICINGA_EXTINFO=$ICINGA_EXTINFO
      - SMOKEPING_URL=$SMOKEPING_URL
      - TIMEZONE=$TIMEZONE
      - MATTERMOST_USERNAME=$MATTERMOST_USERNAME
      - MATTERMOST_HOOK=$MATTERMOST_HOOK
      - GIT_CONFIG_STORE_SSH_URL=$GIT_CONFIG_STORE_SSH_URL
      - SSH_RSA_KEY_BASE=$SSH_RSA_KEY_BASE
      - SSH_RSA_KEY_BASE_PUB=$SSH_RSA_KEY_BASE_PUB
      - SMS_TYPE=$SMS_TYPE
      - SMS_GW_URL=$SMS_GW_URL
      - SMS_GW_USER=$SMS_GW_USER
      - SMS_GW_APIKEY=$SMS_GW_APIKEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - ./data/config:/config
      - ./data/var/lib/icinga:/var/lib/icinga
      - ./data/var/log/icinga:/var/log/icinga
      - ./data/var/cache/icinga:/var/cache/icinga
      - ./data/var/lib/smokeping:/var/lib/smokeping
      - ./data/var/lib/munin:/var/lib/munin
